version: '3.8'

services:
  wildfire-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: alpine:latest
    volumes:
      - wildfire_data:/data
    command: /bin/sh -c "while true; do sleep 3600; done"
    restart: unless-stopped

  # Optional: Add nginx for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - wildfire-api
  #   restart: unless-stopped

volumes:
  wildfire_data:
